In [1]:
import os
import pickle
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

from typing import Tuple
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder, OrdinalEncoder

# set max rows and columns to display
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", 100)

In [42]:
path = "X_train_raw.pkl"

In [44]:
def load_data_checkpoint(path):
    """
    Load picklable object from destination path.

    Parameters
    ----------
    filename : str
        name of the picklable objetc to save.

    path : str
        full path of destination directory.

    Returns
    -------
        Confirmation message.
    """
    if os.path.exists(path):
        with open(path, "rb") as f:
            filename = pickle.load(f)
            print(f"Object loaded successfully from {path}.")
            return filename
    else:
        return print(f"Object or {path} does not exist.")

In [45]:
dataset = load_data_checkpoint(path)

Object loaded successfully from X_train_raw.pkl.


In [5]:
dataset

ID_CLIENT CLERK_TYPE  PAYMENT_DAY APPLICATION_SUBMISSION_TYPE  \
11794      11795          C            1                           0   
24925      24926          C           10                           0   
28578      28579          C            5                           0   
13987      13988          C           20                           0   
7693        7694          C           25                         Web   
...          ...        ...          ...                         ...   
27517      27518          C           10                           0   
28392      28393          C           10                         Web   
5776        5777          C           10                           0   
24864      24865          C           10                         Web   
7756        7757          C           10                           0   

       QUANT_ADDITIONAL_CARDS  POSTAL_ADDRESS_TYPE SEX  MARITAL_STATUS  \
11794                       0                    1   F               1   
24925                       0                    1   F               7   
28578                       0                    1   M               2   
13987                       0                    1   F               6   
7693                        0                    1   F               2   
...                       ...                  ...  ..             ...   
27517                       0                    1   M               1   
28392                       0                    1   M               6   
5776                        0                    1   F               2   
24864                       0                    1   F               1   
7756                        0                    1   F               2   

       QUANT_DEPENDANTS  EDUCATION_LEVEL STATE_OF_BIRTH CITY_OF_BIRTH  \
11794                 0                0                                
24925                 0                0             RS   ENTRE IJUIS   
28578                 2                0             BA       PECANHA   
13987                 1                0             AL     JUNQUEIRO   
7693                  0                0             PE       CARPINA   
...                 ...              ...            ...           ...   
27517                 0                0             PA  CAPITAO POCO   
28392                 0                0             PE      PAUDALHO   
5776                  0                0             MG     VALADARES   
24864                 0                0             SP        PONTAL   
7756                  0                0             PR        GOIORE   

       NACIONALITY RESIDENCIAL_STATE RESIDENCIAL_CITY RESIDENCIAL_BOROUGH  \
11794            0                AP           MACAPA       JD MARCO ZERO   
24925            1                RS    NOVO HAMBURGO        SANTO AFONSO   
28578            1                DF        Ceilandia     Ceilandia Norte   
13987            1                AL           PENEDO          ZONA RURAL   
7693             1                PE          CARPINA            SAO JOSE   
...            ...               ...              ...                 ...   
27517            1                PA      PARAUAPEBAS              DA PAZ   
28392            1                PE         PAUDALHO              CENTRO   
5776             1                MT    VArgem GRANDE           MARIngaum   
24864            1                SP          Guaruja          Vila Zilda   
7756             1                PR        ARAPONGAS            TROPICAL   

      FLAG_RESIDENCIAL_PHONE RESIDENCIAL_PHONE_AREA_CODE  RESIDENCE_TYPE  \
11794                      N                                         5.0   
24925                      Y                          54             1.0   
28578                      Y                          66             1.0   
13987                      Y                         100             4.0   
7693                       Y                          97             1.

In [8]:
import json

path_json_test = "json_example.json"
def load_json(path_json_test):

    if os.path.exists(path_json_test):
        with open(path_json_test, "rb") as f:
            filename = json.load(f)
            print(f"Object loaded successfully from {path_json_test}.")
            return filename
    else:
        return print(f"Object or {path_json_test} does not exist.")
json = load_json(path_json_test)

Object loaded successfully from json_example.json.


In [9]:
# conver json to dataframe
df_to_predict = pd.DataFrame.from_dict(json, orient='index')
df_to_predict = df_to_predict.transpose()
df_to_predict

ID_CLIENT PAYMENT_DAY APPLICATION_SUBMISSION_TYPE QUANT_ADDITIONAL_CARDS  \
0         1           1                         Web                      2   

  POSTAL_ADDRESS_TYPE SEX MARITAL_STATUS QUANT_DEPENDANTS EDUCATION_LEVEL  \
0                   1   M              1                3               1   

  NACIONALITY FLAG_RESIDENCIAL_PHONE RESIDENCE_TYPE MONTHS_IN_RESIDENCE  \
0           1                      N              2                   1   

  FLAG_EMAIL PERSONAL_MONTHLY_INCOME OTHER_INCOMES FLAG_VISA FLAG_MASTERCARD  \
0          0                       1             1         0               1   

  FLAG_DINERS FLAG_AMERICAN_EXPRESS FLAG_OTHER_CARDS QUANT_BANKING_ACCOUNTS  \
0           0                     0                0                      0   

  QUANT_SPECIAL_BANKING_ACCOUNTS PERSONAL_ASSETS_VALUE QUANT_CARS COMPANY  \
0                              1                     1          1       Y   

  FLAG_PROFESSIONAL_PHONE PROFESSIONAL_PHONE_AREA_CODE MONTHS_IN_THE_JOB  \
0                       N                            1                 1   

  PROFESSION_CODE OCCUPATION_TYPE FLAG_HOME_ADDRESS_DOCUMENT FLAG_RG FLAG_CPF  \
0               1               4                          0       1        0   

  FLAG_INCOME_PROOF PRODUCT AGE TARGET_LABEL_BAD  
0                 0       1  18                0

In [10]:
dataset.sample(1)

ID_CLIENT CLERK_TYPE  PAYMENT_DAY APPLICATION_SUBMISSION_TYPE  \
35241      35242          C           15                           0   

       QUANT_ADDITIONAL_CARDS  POSTAL_ADDRESS_TYPE SEX  MARITAL_STATUS  \
35241                       0                    1   F               2   

       QUANT_DEPENDANTS  EDUCATION_LEVEL STATE_OF_BIRTH        CITY_OF_BIRTH  \
35241                 0                0             RN  RIO GRANDE DO NORTE   

       NACIONALITY RESIDENCIAL_STATE RESIDENCIAL_CITY RESIDENCIAL_BOROUGH  \
35241            1                DF             GAMA           SETOR SUL   

      FLAG_RESIDENCIAL_PHONE RESIDENCIAL_PHONE_AREA_CODE  RESIDENCE_TYPE  \
35241                      Y                          66             1.0   

       MONTHS_IN_RESIDENCE FLAG_MOBILE_PHONE  FLAG_EMAIL  \
35241                 30.0                 N           0   

       PERSONAL_MONTHLY_INCOME  OTHER_INCOMES  FLAG_VISA  FLAG_MASTERCARD  \
35241                    450.0            0.0          0                0   

       FLAG_DINERS  FLAG_AMERICAN_EXPRESS  FLAG_OTHER_CARDS  \
35241            0                      0                 0   

       QUANT_BANKING_ACCOUNTS  QUANT_SPECIAL_BANKING_ACCOUNTS  \
35241                       1                               1   

       PERSONAL_ASSETS_VALUE  QUANT_CARS COMPANY PROFESSIONAL_STATE  \
35241                    0.0           1       N                      

      PROFESSIONAL_CITY PROFESSIONAL_BOROUGH FLAG_PROFESSIONAL_PHONE  \
35241               NaN                  NaN                       N   

      PROFESSIONAL_PHONE_AREA_CODE  MONTHS_IN_THE_JOB  PROFESSION_CODE  \
35241                                               0              0.0   

       OCCUPATION_TYPE  MATE_PROFESSION_CODE  MATE_EDUCATION_LEVEL  \
35241              0.0                   0.0                   0.0   

       FLAG_HOME_ADDRESS_DOCUMENT  FLAG_RG  FLAG_CPF  FLAG_INCOME_PROOF  \
35241                           0        0         0                  0   

       PRODUCT FLAG_ACSP_RECORD  AGE RESIDENCIAL_ZIP_3 PROFESSIONAL_ZIP_3  
35241        1                N   45               724                724

In [12]:
print(dataset.shape, df_to_predict.shape)

(32000, 53) (1, 38)


In [12]:
chck = {
'ID_CLIENT' : 1, # Esto debe agregarse
'PAYMENT_DAY': 2,# Esto debe agregarse
"APPLICATION_SUBMISSION_TYPE": "Web",
"QUANT_ADDITIONAL_CARDS": 2,
"POSTAL_ADDRESS_TYPE": 1,
"SEX": "M",
"MARITAL_STATUS": 1,
"QUANT_DEPENDANTS": 3,
"EDUCATION_LEVEL": 1,
"NACIONALITY": 1,
"FLAG_RESIDENCIAL_PHONE": "N", 
"RESIDENCE_TYPE": 2,
"MONTHS_IN_RESIDENCE": 1,
"FLAG_EMAIL": 0,
"PERSONAL_MONTHLY_INCOME": 1,
"OTHER_INCOMES": 1,
"FLAG_VISA": 0,
"FLAG_MASTERCARD": 1,
"FLAG_DINERS": 0,
"FLAG_AMERICAN_EXPRESS": 0,
"FLAG_OTHER_CARDS": 0,
"QUANT_BANKING_ACCOUNTS": 0,
"QUANT_SPECIAL_BANKING_ACCOUNTS": 1,
"PERSONAL_ASSETS_VALUE": 1,
"QUANT_CARS": 1,
"COMPANY": "Y",
"FLAG_PROFESSIONAL_PHONE": "N",
"PROFESSIONAL_PHONE_AREA_CODE": 1,
"MONTHS_IN_THE_JOB": 1,
"PROFESSION_CODE": 1,
"OCCUPATION_TYPE": 4,
"FLAG_HOME_ADDRESS_DOCUMENT": 0,
"FLAG_RG": 1, "FLAG_CPF": 0,
"FLAG_INCOME_PROOF": 0,
"PRODUCT": 1,
"AGE": 18,
"TARGET_LABEL_BAD": 0}

In [13]:
#Binary and Multi-Class Columns
binary_cols=[]
multi_cols=[]
categorical_cols = dataset.select_dtypes(include='object').columns.tolist()
for cat_col in categorical_cols:
        unique_values = dataset[cat_col].nunique()
        if unique_values==1 or unique_values>=20:
            dataset=dataset.drop(cat_col,axis=1)
        if unique_values==2:
            binary_cols.append(cat_col)
        if unique_values>=3 and unique_values<20:
            multi_cols.append(cat_col)

print(binary_cols, multi_cols)      

['FLAG_RESIDENCIAL_PHONE', 'COMPANY', 'FLAG_PROFESSIONAL_PHONE'] ['APPLICATION_SUBMISSION_TYPE', 'SEX']


In [14]:
print(dataset.shape, df_to_predict.shape)

(32000, 38) (1, 38)


In [18]:
# df_to_predict.drop(columns=['TARGET_LABEL_BAD', 'PROFESSIONAL_PHONE_AREA_CODE'], inplace=True)

In [19]:
# dataset.drop(columns=['ID_CLIENT', 'PAYMENT_DAY'], inplace=True)

In [18]:
print(dataset.shape, df_to_predict.shape)

(32000, 38) (1, 38)


In [19]:
print(dataset.shape, dataset.columns.tolist())

(32000, 38) ['ID_CLIENT', 'PAYMENT_DAY', 'APPLICATION_SUBMISSION_TYPE', 'QUANT_ADDITIONAL_CARDS', 'POSTAL_ADDRESS_TYPE', 'SEX', 'MARITAL_STATUS', 'QUANT_DEPENDANTS', 'EDUCATION_LEVEL', 'NACIONALITY', 'FLAG_RESIDENCIAL_PHONE', 'RESIDENCE_TYPE', 'MONTHS_IN_RESIDENCE', 'FLAG_EMAIL', 'PERSONAL_MONTHLY_INCOME', 'OTHER_INCOMES', 'FLAG_VISA', 'FLAG_MASTERCARD', 'FLAG_DINERS', 'FLAG_AMERICAN_EXPRESS', 'FLAG_OTHER_CARDS', 'QUANT_BANKING_ACCOUNTS', 'QUANT_SPECIAL_BANKING_ACCOUNTS', 'PERSONAL_ASSETS_VALUE', 'QUANT_CARS', 'COMPANY', 'FLAG_PROFESSIONAL_PHONE', 'MONTHS_IN_THE_JOB', 'PROFESSION_CODE', 'OCCUPATION_TYPE', 'MATE_PROFESSION_CODE', 'MATE_EDUCATION_LEVEL', 'FLAG_HOME_ADDRESS_DOCUMENT', 'FLAG_RG', 'FLAG_CPF', 'FLAG_INCOME_PROOF', 'PRODUCT', 'AGE']


In [20]:
print(df_to_predict.shape, df_to_predict.columns.tolist())

(1, 38) ['ID_CLIENT', 'PAYMENT_DAY', 'APPLICATION_SUBMISSION_TYPE', 'QUANT_ADDITIONAL_CARDS', 'POSTAL_ADDRESS_TYPE', 'SEX', 'MARITAL_STATUS', 'QUANT_DEPENDANTS', 'EDUCATION_LEVEL', 'NACIONALITY', 'FLAG_RESIDENCIAL_PHONE', 'RESIDENCE_TYPE', 'MONTHS_IN_RESIDENCE', 'FLAG_EMAIL', 'PERSONAL_MONTHLY_INCOME', 'OTHER_INCOMES', 'FLAG_VISA', 'FLAG_MASTERCARD', 'FLAG_DINERS', 'FLAG_AMERICAN_EXPRESS', 'FLAG_OTHER_CARDS', 'QUANT_BANKING_ACCOUNTS', 'QUANT_SPECIAL_BANKING_ACCOUNTS', 'PERSONAL_ASSETS_VALUE', 'QUANT_CARS', 'COMPANY', 'FLAG_PROFESSIONAL_PHONE', 'PROFESSIONAL_PHONE_AREA_CODE', 'MONTHS_IN_THE_JOB', 'PROFESSION_CODE', 'OCCUPATION_TYPE', 'FLAG_HOME_ADDRESS_DOCUMENT', 'FLAG_RG', 'FLAG_CPF', 'FLAG_INCOME_PROOF', 'PRODUCT', 'AGE', 'TARGET_LABEL_BAD']


In [21]:
ord_encoder = OrdinalEncoder()
for col in binary_cols:
    dataset[col] = ord_encoder.fit_transform(dataset[[col]].fillna('Unknown'))
    df_to_predict[col] = ord_encoder.transform(df_to_predict[[col]].fillna('Unknown'))

In [22]:
#OneHotEncoder for Multi-Class Columns
oh_encoder = OneHotEncoder(handle_unknown="ignore")
oh_encoder.fit(dataset[multi_cols])
# oh_encoder.fit(df_to_predict[multi_cols])

OneHotEncoder(handle_unknown='ignore')

In [23]:
print(dataset.shape, df_to_predict.shape)

(32000, 38) (1, 38)


In [24]:
dataset_cols = oh_encoder.transform(dataset[multi_cols]).toarray()
df_to_predict_cols = oh_encoder.transform(df_to_predict[multi_cols]).toarray()

In [25]:
print(dataset_cols.shape, df_to_predict_cols.shape)

(32000, 7) (1, 7)


In [26]:
dataset.drop(columns=multi_cols, axis=1, inplace=True)
df_to_predict.drop(columns=multi_cols, axis=1, inplace=True)

In [27]:
print(dataset_cols.shape, df_to_predict_cols.shape)

(32000, 7) (1, 7)


In [28]:
dataset = np.concatenate([dataset.to_numpy(), dataset_cols],axis=1)
df_to_predict = np.concatenate([df_to_predict.to_numpy(), df_to_predict_cols],axis=1)

In [29]:
print(dataset.shape, df_to_predict.shape)

(32000, 43) (1, 43)


In [30]:
#Impute Data for Columns with Missing Data
imputer=SimpleImputer(missing_values=np.nan,strategy="most_frequent")
imputer.fit(dataset)

SimpleImputer(strategy='most_frequent')

In [31]:
df_to_predict=imputer.transform(df_to_predict)

In [32]:
scaler=MinMaxScaler(feature_range=(0,1))
scaler.fit(dataset)

MinMaxScaler()

In [33]:
df_to_predict=scaler.transform(df_to_predict)

In [34]:
print(dataset.shape, df_to_predict.shape)

(32000, 43) (1, 43)


In [35]:
print(dataset,"--", df_to_predict)

[[1.1795e+04 1.0000e+00 0.0000e+00 ... 1.0000e+00 0.0000e+00 0.0000e+00]
 [2.4926e+04 1.0000e+01 0.0000e+00 ... 1.0000e+00 0.0000e+00 0.0000e+00]
 [2.8579e+04 5.0000e+00 0.0000e+00 ... 0.0000e+00 1.0000e+00 0.0000e+00]
 ...
 [5.7770e+03 1.0000e+01 0.0000e+00 ... 1.0000e+00 0.0000e+00 0.0000e+00]
 [2.4865e+04 1.0000e+01 0.0000e+00 ... 1.0000e+00 0.0000e+00 0.0000e+00]
 [7.7570e+03 1.0000e+01 0.0000e+00 ... 1.0000e+00 0.0000e+00 0.0000e+00]] -- [[ 0.00000000e+00  0.00000000e+00  2.00000000e+00  0.00000000e+00
   1.42857143e-01  2.00000000e-01  1.00000000e+00  5.00000000e-01
   0.00000000e+00  4.00000000e-01  5.00000000e-03  0.00000000e+00
  -8.83312872e-05  5.14551517e-06  0.00000000e+00  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   5.00000000e-01  1.66666667e-07  1.00000000e+00  1.00000000e+00
   0.00000000e+00  2.85714286e-02  5.55555556e-02  2.00000000e-01
   2.50000000e-01  0.00000000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00  1.0000

In [39]:
import mlflow
import mlflow.pyfunc

model_path = "93c9d5110ad34c91ac778aa0c88eb2b4/artifacts/lightgbm"  # Reemplaza <RUN_ID> con el ID de la ejecución de tu modelo.
model = mlflow.pyfunc.load_model(model_path)

2023/06/04 21:45:00 WARNING mlflow.pyfunc: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - mlflow (current: 2.3.2, required: mlflow==2.3)
 - lightgbm (current: 3.3.5, required: lightgbm==3.3.3)
 - matplotlib (current: 3.6.2, required: matplotlib==3.5.3)
 - numpy (current: 1.24.3, required: numpy==1.20.0)
 - pandas (current: 1.5.2, required: pandas==1.4.3)
 - psutil (current: 5.9.5, required: psutil==5.9.4)
 - scipy (current: 1.9.3, required: scipy==1.9.0)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.


In [40]:
# Realizar una predicción con el modelo
prediction = model.predict(df_to_predict)

# Imprimir la predicción
print(prediction)

[0.50242037]
